vich_uploader:
    db_driver: orm

    mappings:
        user_csv:
            uri_prefix: '%app.path.user_csv%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_csv%'
            namer: vich_uploader.namer_uniqid